# Tasks for deploying PostgreSQL configuration files
- name: Deploy PostgreSQL.conf
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_conf_file }}"
    owner: postgres
    group: postgres
    mode: '0644'
  notify: Restart PostgreSQL

- name: Deploy Pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ pg_hba_conf_file }}"
    owner: postgres
    group: postgres
    mode: '0640'
  notify: Restart PostgreSQL


