- name: Deploy postgresql.conf
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_conf_file }}"
  notify: restart postgresql

- name: Deploy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{ pg_hba_conf_file }}"
  notify: restart postgresql
